stages:
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - target/
    - .cargo/
    - .rustup/

cargo-build:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y curl build-essential
    - export CARGO_HOME=$CI_PROJECT_DIR/.cargo  # Ensure the environment variables are set
    - export RUSTUP_HOME=$CI_PROJECT_DIR/.rustup
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - source $CI_PROJECT_DIR/.cargo/env
  script:
    - cargo build --release
  artifacts:
    when: on_success
    paths:
      - target/release/
      - .cargo/
      - .rustup/

cargo-test:
  stage: test
  image: debian:stable-slim
  before_script:
    - apt-get update
    - apt-get install -y curl build-essential
    - export CARGO_HOME=$CI_PROJECT_DIR/.cargo  # Ensure cargo uses the correct directory
    - export RUSTUP_HOME=$CI_PROJECT_DIR/.rustup
    - source $CI_PROJECT_DIR/.cargo/env
  script:
    - cargo test
  dependencies:
    - cargo-build
