stages:
  - build
  - test

cargo-build:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y curl build-essential
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - source $HOME/.cargo/env
    - cargo install sqlx-cli
  script:
    - DATABASE_URL=sqlite://test.sqlite cargo sqlx database create
    - DATABASE_URL=sqlite://test.sqlite cargo sqlx migrate run
    - DATABASE_URL=sqlite://test.sqlite cargo sqlx prepare
    - cargo build --release

cargo-test:
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y curl build-essential
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - source $HOME/.cargo/env
    - cargo install sqlx-cli
  script:
    - DATABASE_URL=sqlite://test.sqlite cargo sqlx database create
    - DATABASE_URL=sqlite://test.sqlite cargo sqlx migrate run
    - DATABASE_URL=sqlite://test.sqlite cargo sqlx prepare
    - cargo test
