stages:
  - build
  - test

cargo-build:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y curl build-essential
    - curl https://sh.rustup.rs -sSf | sh -s -- -y
    - source $HOME/.cargo/env
  script:
    - cargo build
  artifacts:
    paths:
      - $HOME/.cargo
      - $HOME/.rustup
    when: on_success
    access: none
    expire_in: 1 days

cargo-test:
  stage: test
  before_script:
    - source $HOME/.cargo/env
  script:
    - cargo test
  dependencies:
    - cargo-build
