[package]
name = "p2p_file_sync"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
dir = "0.1.2"
dirs = "5.0.1"
env_logger = "0.11.5"
eyre = "0.6.12"
log = "0.4.22"
notify = "6.1.1"
serde = { version = "1", features = ["derive"] }
thiserror = "1.0.65"
toml = "0.8.19"
