services:
    p2p-node1:
        build: .
        networks:
            p2p-network:
                ipv4_address: 172.20.0.2
        environment:
            - RUST_BACKTRACE=1
        volumes:
          - ./docker/config_node1.toml:/home/ubuntu/.config/p2p/config.toml:rw
          - ./docker/node1_sync/:/home/ubuntu/peer1/documents:rw
        command: cargo run --release
        ports:
          - 3617:3617

    p2p-node2:
        build: .
        networks:
            p2p-network:
                ipv4_address: 172.20.0.3
        environment:
            - RUST_BACKTRACE=1
        volumes:
          - ./docker/config_node2.toml:/home/ubuntu/.config/p2p/config.toml:rw
          - ./docker/node2_sync/:/home/ubuntu/peer2/documents:rw
        command: cargo run --release

networks:
    p2p-network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16
